#
# Interval is in Seconds not Ticks*
#

messages:
  - text: "Â§eHey! this server and a lot of its plugins are made by me solo, if you would like to help cover some overhead costs, i would love it if you visited our Ko-Fi page, https://ko-fi.com/mellurboo"
    interval: 900